### ISSUE TITLE
我日，大哥，你传错项目了

### ISSUE THREAD

**Issue by fg2q1q3q** [103style/QQ6.1GestureLock#1]

**Comment by 103style** [comment]
没错啊...

2016-10-31 11:59 GMT+08:00 Barry notifications@github.com:

**Comment by 103style** [comment]
没错啊

**Comment by fg2q1q3q** [comment]
错了！！！你运行看看就知道了，根本不是qq手势密码，好在我通过csdn下载到了，但是这里传的是错的

**Comment by 103style** [comment]
@fg2q1q3q   不好意思    在改了...

**Comment by 103style** [comment]
@fg2q1q3q   抱歉

**Comment by fg2q1q3q** [comment]
ok，三克油，辛苦，已star
